# Generated by Django 2.2.28 on 2023-06-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrty', models.BigIntegerField()),
            ],
        ),
    ]
