# Generated by Django 2.2.28 on 2023-06-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vder',
        ),
    ]
