# Generated by Django 2.2.28 on 2023-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_vder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bvcer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnhj', models.BigIntegerField()),
            ],
        ),
    ]
